[package]
name = "kernel"
version = "0.1.0"
authors = ["mark"]

[dependencies]
rlibc = "*"

[lib]
name = "kernel"
path = "lib.rs"
crate-type = ["staticlib"]

[profile.dev]
panic = "unwind"

[profile.release]
panic = "unwind"
